/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package git_test;

import java.awt.CardLayout;
import git_test.*;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.BorderFactory;

/**
 *
 * @author davs
 */
public class CardGUI extends javax.swing.JFrame {

    /**
     * Creates new form CardGUI
     */
    public CardGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        jButton7.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        jButton7.setText("Klik her for Shopping");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Trattatello", 0, 43)); // NOI18N
        jLabel3.setText("Velkommen til  Næstveds Tøjmagasin ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );

        jPanel1.add(jPanel5, "card5");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Tilføj vare");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bukser", "Skjorter", "T-Shirts" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("færdig");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Farve" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Størrelse" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Produkt Navn" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel4.setText("Størrelse");

        jLabel5.setText("Farve");

        jLabel6.setText("Produkt Navn");

        jLabel7.setText("Produkt Type");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Indkøbskurv");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(83, 83, 83))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(447, 447, 447)
                            .addComponent(jButton2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(13, 13, 13)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jButton3.setText("Betal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setText("Fornavn");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("Efternavn");

        jTextField3.setText("E-Mail");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2020", "2021", "2022", "2023" }));

        jTextField4.setText("Kort nummer");

        jTextField5.setText("Adresse");

        jTextField6.setText("Postnummer");

        jTextField7.setText("Sikkerhedskode");

        jTextField8.setText("Tlf");

        jLabel2.setText("/");

        jTextField9.setText("nr");

        jButton8.setText("Fortryd");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dankort", "MasterCard" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel9.setText("Kort type");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                        .addComponent(jTextField3)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField9))
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton3))
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel3, "card3");

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Trattatello", 1, 24)); // NOI18N
        jLabel1.setText("Tusinde tak for din ordre, vi håber du bliver tilfreds med varen");

        jButton4.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        jButton4.setText("Shop mere");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.next(jPanel1);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextArea1.setText("");
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.next(jPanel1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean fornavn = false;
        if (jTextField1.getText().matches("[a-zA-Z]+")) {
            fornavn = true;
            jTextField1.setBorder(null);
            jTextField1.updateUI();
        } else {
            jTextField1.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }

        boolean efternavn = false;
        if (jTextField2.getText().matches("[a-zA-Z]+")) {
            efternavn = true;

            jTextField2.getBorder();
        } else {
            jTextField2.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }
        //det der pis virker sku ik, find ud af hvordan vi både kan ha tal, bogstaver og tegn i textfieldet.
        /*boolean email = false;
         if (jTextField3.getText().matches("[HER FUCKER DET OP]+")) {
         email = true;
         }
         else { jTextField3.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
         }*/
        boolean tlf = false;
        if (jTextField8.getText().matches("[0-9]+")) {
            tlf = true;

            jTextField8.getBorder();
        } else {
            jTextField8.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }
        boolean adresse = false;
        if (jTextField5.getText().matches("[a-zA-Z]+")) {
            adresse = true;

            jTextField5.getBorder();
        } else {
            jTextField5.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }
        boolean nr = false;
        if (jTextField9.getText().matches("[a-zA-Z_0-9]+")) {
            nr = true;

            jTextField9.getBorder();
        } else {
            jTextField9.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }
        boolean postnummer = false;
        if (jTextField6.getText().matches("[0-9]+")) {
            postnummer = true;

            jTextField6.getBorder();
        } else {
            jTextField6.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }
        boolean kortnummer = false;
        if (jTextField4.getText().matches("[0-9]+")) {
            kortnummer = true;

            jTextField4.getBorder();
        } else {
            jTextField4.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }
        boolean sikkerhedskode = false;
        if (jTextField7.getText().matches("[0-9]+")) {
            sikkerhedskode = true;

            jTextField7.getBorder();
        } else {
            jTextField7.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }

        CardLayout cl = (CardLayout) jPanel1.getLayout();
        Receit receit = new Receit();
        receit.printOrder();
        if (fornavn && efternavn /*&& email*/ && tlf && adresse && nr && postnummer && kortnummer && sikkerhedskode) // Lige her skal Receit koden sættes så den printer nær man trykker betal
        //men først efter informationerne er tjekket at de passer, der for lige her.
          {
            cl.next(jPanel1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.append(jComboBox1.getSelectedItem().toString() + " ");
        jTextArea1.append(jComboBox6.getSelectedItem().toString() + " ");
        jTextArea1.append(jComboBox3.getSelectedItem().toString() + " ");
        jTextArea1.append(jComboBox2.getSelectedItem().toString() + "\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    private void updateSizes() {
        String type;
      
            type = (String) jComboBox6.getSelectedItem();
            switch (type) {
                case "Jeans":
                    jComboBox3.removeAllItems();

                    String[] items24 = new String[]{"28", "29", "31", "33", "36"};
                    for (String item24 : items24) {
                        jComboBox3.addItem(item24);
                    }
                    break;

                case "Chinos":
                    jComboBox3.removeAllItems();

                    String[] items25 = new String[]{"29", "30", "32", "34", "38"};
                    for (String item25 : items25) {
                        jComboBox3.addItem(item25);
                    }
                    break;

                case "Læderbukser":
                    jComboBox3.removeAllItems();

                    String[] items26 = new String[]{"28", "31", "32", "34", "36"};
                    for (String item26 : items26) {
                        jComboBox3.addItem(item26);
                    }
                    break;

                case "Cargo":
                    jComboBox3.removeAllItems();

                    String[] items7 = new String[]{"29", "30", "33", "34", "38"};
                    for (String item7 : items7) {
                        jComboBox3.addItem(item7);
                    }
                    break;

                case "Fløjlsbukser":
                    jComboBox3.removeAllItems();

                    String[] items8 = new String[]{"28", "29", "30", "31", "33"};
                    for (String item8 : items8) {
                        jComboBox3.addItem(item8);
                    }
                    break;

                case "Habitbukser":
                    jComboBox3.removeAllItems();

                    String[] items9 = new String[]{"28", "32", "33", "36", "38"};
                    for (String item9 : items9) {
                        jComboBox3.addItem(item9);
                    }
                    break;

                case "Sweatpants":
                    jComboBox3.removeAllItems();

                    String[] items10 = new String[]{"29", "31", "32", "34", "38"};
                    for (String item10 : items10) {
                        jComboBox3.addItem(item10);
                    }
                    break;
                //----Skjorter-----
                case "Bomuldsskjorte":
                    jComboBox3.removeAllItems();

                    String[] items11 = new String[]{"38", "39", "40", "42", "44", "54"};
                    for (String item11 : items11) {
                        jComboBox3.addItem(item11);
                    }
                    break;

                case "Denimskjorte":
                    jComboBox3.removeAllItems();

                    String[] items12 = new String[]{"38", "39", "41", "43", "44", "45"};
                    for (String item12 : items12) {
                        jComboBox3.addItem(item12);
                    }
                    break;

                case "Cottonskjorte":
                    jComboBox3.removeAllItems();

                    String[] items13 = new String[]{"38", "40", "42", "43", "44", "45"};
                    for (String item13 : items13) {
                        jComboBox3.addItem(item13);
                    }
                    break;

                case "Flonelskjorte":
                    jComboBox3.removeAllItems();

                    String[] items14 = new String[]{"39", "41", "42", "43", "44", "45"};
                    for (String item14 : items14) {
                        jComboBox3.addItem(item14);
                    }
                    break;

                case "Twillskjorte":
                    jComboBox3.removeAllItems();

                    String[] items15 = new String[]{"38", "40", "41", "42", "43", "44"};
                    for (String item15 : items15) {
                        jComboBox3.addItem(item15);
                    }
                    break;

                case "Oxfordskjorte":
                    jComboBox3.removeAllItems();

                    String[] items16 = new String[]{"39", "40", "41", "42", "43", "45"};
                    for (String item16 : items16) {
                        jComboBox3.addItem(item16);
                    }
                    break;
                //----T-SHIRTS----
                case "Basis T-Shirt":
                    jComboBox3.removeAllItems();

                    String[] items17 = new String[]{"S", "M", "L", "XXL"};
                    for (String item17 : items17) {
                        jComboBox3.addItem(item17);
                    }
                    break;

                case "T-shirt med V-udskæring":
                    jComboBox3.removeAllItems();

                    String[] items18 = new String[]{"S", "M", "L", "LX"};
                    for (String item18 : items18) {
                        jComboBox3.addItem(item18);
                    }
                    break;

                case "T-shirt med Stretch":
                    jComboBox3.removeAllItems();

                    String[] items19 = new String[]{"M", "L", "XL", "XXL"};
                    for (String item19 : items19) {
                        jComboBox3.addItem(item19);
                    }
                    break;

                case "Lang T-shirt":
                    jComboBox3.removeAllItems();

                    String[] items20 = new String[]{"S", "L", "XL", "XXL"};
                    for (String item20 : items20) {
                        jComboBox3.addItem(item20);
                    }
                    break;

                case "T-shirt med tryk":
                    jComboBox3.removeAllItems();

                    String[] items21 = new String[]{"S", "M", "XL", "XXL"};
                    for (String item21 : items21) {
                        jComboBox3.addItem(item21);
                    }
                    break;

                case "Stribet T-shirt":
                    jComboBox3.removeAllItems();

                    String[] items22 = new String[]{"S", "M", "L", "XXL"};
                    for (String item22 : items22) {
                        jComboBox3.addItem(item22);
                    }
                    break;

                case "T-shirt i vaffelstrik":
                    jComboBox3.removeAllItems();

                    String[] items23 = new String[]{"S", "M", "L", "XL"};
                    for (String item23 : items23) {
                        jComboBox3.addItem(item23);
                    }
                    break;
            }
        
    }
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed

    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void updateColors() {
        String type;

        type = (String) jComboBox6.getSelectedItem();
        switch (type) {
            case "Jeans":
                jComboBox2.removeAllItems();

                String[] items4 = new String[]{"Sort", "Grå", "Blå", "Hvid"};
                for (String item4 : items4) {
                    jComboBox2.addItem(item4);
                }
                break;

            case "Chinos":
                jComboBox2.removeAllItems();

                String[] items5 = new String[]{"Rød", "Brun", "Grå", "Gul"};
                for (String item5 : items5) {
                    jComboBox2.addItem(item5);
                }
                break;

            case "Læderbukser":
                jComboBox2.removeAllItems();

                String[] items6 = new String[]{"Sort", "Rød", "Grøn"};
                for (String item6 : items6) {
                    jComboBox2.addItem(item6);
                }
                break;

            case "Cargo":
                jComboBox2.removeAllItems();

                String[] items7 = new String[]{"Brun", "Grøn", "Blå", "Gul"};
                for (String item7 : items7) {
                    jComboBox2.addItem(item7);
                }
                break;

            case "Fløjlsbukser":
                jComboBox2.removeAllItems();

                String[] items8 = new String[]{"Rød", "Brun", "Grå", "Gul"};
                for (String item8 : items8) {
                    jComboBox2.addItem(item8);
                }
                break;

            case "Habitbukser":
                jComboBox2.removeAllItems();

                String[] items9 = new String[]{"Sort", "Grå", "Hvid"};
                for (String item9 : items9) {
                    jComboBox2.addItem(item9);
                }
                break;

            case "Sweatpants":
                jComboBox2.removeAllItems();

                String[] items10 = new String[]{"Sort", "Grå", "Rød", "Blå", "Brun"};
                for (String item10 : items10) {
                    jComboBox2.addItem(item10);
                }
                break;
            //OKAY NU GÅR VI OVER TIL Skjorter
            case "Bomuldsskjorte":
                jComboBox2.removeAllItems();

                String[] items11 = new String[]{"Sort", "Blå", "Rød"};
                for (String item11 : items11) {
                    jComboBox2.addItem(item11);
                }
                break;

            case "Denimskjorte":
                jComboBox2.removeAllItems();

                String[] items12 = new String[]{"Grå", "Grøn", "Hvid", "Turkis"};
                for (String item12 : items12) {
                    jComboBox2.addItem(item12);
                }
                break;

            case "Cottonskjorte":
                jComboBox2.removeAllItems();

                String[] items13 = new String[]{"Blå", "Gul", "Lyserød", "Brun"};
                for (String item13 : items13) {
                    jComboBox2.addItem(item13);
                }
                break;

            case "Flonelskjorte":
                jComboBox2.removeAllItems();

                String[] items14 = new String[]{"Grøn", "Rød", "Lime", "Sort"};
                for (String item14 : items14) {
                    jComboBox2.addItem(item14);
                }
                break;

            case "Twillskjorte":
                jComboBox2.removeAllItems();

                String[] items15 = new String[]{"Gul", "Hvid", "Turkis", "Grå"};
                for (String item15 : items15) {
                    jComboBox2.addItem(item15);
                }
                break;

            case "Oxfordskjorte":
                jComboBox2.removeAllItems();

                String[] items16 = new String[]{"Rød", "Lyserød", "Brun", "Blå"};
                for (String item16 : items16) {
                    jComboBox2.addItem(item16);
                }
                break;
                
            //OG NU LAVER VI T-SHIRTS
            case "Basis T-Shirt":
                jComboBox2.removeAllItems();

                String[] items17 = new String[]{"Hvid", "Lime", "Sort", "Grøn"};
                for (String item17 : items17) {
                    jComboBox2.addItem(item17);
                }
                break;

            case "T-shirt med V-udskæring":
                jComboBox2.removeAllItems();

                String[] items18 = new String[]{"Lyserød", "Turkis", "Grå", "Gul"};
                for (String item18 : items18) {
                    jComboBox2.addItem(item18);
                }
                break;

            case "T-shirt med Stretch":
                jComboBox2.removeAllItems();

                String[] items19 = new String[]{"Lime", "Brun", "Blå", "Rød"};
                for (String item19 : items19) {
                    jComboBox2.addItem(item19);
                }
                break;

            case "Lang T-shirt":
                jComboBox2.removeAllItems();

                String[] items20 = new String[]{"Turkis", "Sort", "Grøn", "Hvid"};
                for (String item20 : items20) {
                    jComboBox2.addItem(item20);
                }
                break;

            case "T-shirt med tryk":
                jComboBox2.removeAllItems();

                String[] items21 = new String[]{"Brun", "Grå", "Gul", "Sort"};
                for (String item21 : items21) {
                    jComboBox2.addItem(item21);
                }
                break;

            case "Stribet T-shirt":
                jComboBox2.removeAllItems();

                String[] items22 = new String[]{"Sort", "Blå", "Rød"};
                for (String item22 : items22) {
                    jComboBox2.addItem(item22);
                }
                break;

            case "T-shirt i vaffelstrik":
                jComboBox2.removeAllItems();

                String[] items23 = new String[]{"Grå", "Grøn", "Hvid", "Turkis"};
                for (String item23 : items23) {
                    jComboBox2.addItem(item23);
                }
                break;
        }
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String type;
        type = (String) jComboBox1.getSelectedItem();
        switch (type) {
            case "Bukser":
                jComboBox6.removeAllItems();

                String[] items = new String[]{"Jeans", "Cinos", "Læderbukser", "Cargo", "Fjøjlsbukser", "Habitbukser", "Sweatpants"};
                for (String item : items) {
                    jComboBox6.addItem(item);
                }
                break;

            case "Skjorter":
                jComboBox6.removeAllItems();

                String[] items2 = new String[]{"Bomuldsskjorte", "Denimskjorte", "Cottonskjorte", "Flonelskjorte", "Twillskjorte", "Oxfordskjorte"};
                for (String item2 : items2) {
                    jComboBox6.addItem(item2);
                }
                break;
            //jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(String[]{"Bomuldsskjorte", "Denimskjorte", "Cottonskjorte", "Flonelskjorte", "Twillskjorte", "Oxfordskjorte"}));
            case "T-Shirts":
                jComboBox6.removeAllItems();

                String[] items3 = new String[]{"Basis T-Shirt", "T-Shirt med V-udskæring", "T-Shirt med Stretch", "Lang T-Shirt", "T-Shirt med tryk", "Stribet T-Shirt", "T-Shirt i vaffelstrik"};
                for (String item3 : items3) {
                    jComboBox6.addItem(item3);
                }
                break;
                //jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(String[]{"Basis T-Shirt", "T-Shirt med V-udskæring", "T-Shirt med Stretch", "Lang T-Shirt", "T-Shirt med tryk", "Stribet T-Shirt", "T-Shirt i vaffelstrik"}));
            //Her mangler kode til combobox, så de viser forskellige informationer
            //alt efter produkt farve og størrelse. Vi skal huske at tilføje pris til varene.

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.next(jPanel1);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.previous(jPanel1);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // Her Skal være noget kode til Mastercard og Dankort
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        if (jComboBox6.getItemCount() > 0) {
            updateSizes();
            updateColors();
        }
    }//GEN-LAST:event_jComboBox6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
